#ここにライブラリとして記述する
#start.rbに入れました

class Click_coffee
  constructor: (@object) ->
    alert @object
    alert "start.rbで実行してるんやで"
  story1: ->
    $(@object).click =>
      alert @object
      alert 123
###
aa = new TestCtrl ("#btn12")
aa.story1()
###   
# rakefileでやりました

######TestCtrlの中身######
# ここからTestCtrlの中身ですね
class TestCtrl
  constructor: ->
    #alert "okべいび"
    
  story1: ->
    alert "story1です"
  
  story2: ->
    ###
    document.addEventListener("deviceready", onDeviceReady, false)
    db = window.openDatabase("database", "1.0", "testdatabase", 1000000);
    ###
    name = 'localdb'
    version = '1.0'
    description = 'Web SQL Database'
    size = 2 * 1024 * 1024
    db = openDatabase(name, version, description, size)
    
    db.transaction (tx) ->
      tx.executeSql 'insert into user (id, name) values (?, ?)', [1, '金田']
  
  story3: ->



######################################
#表示させるクラス
class Disp
  constructor: (@id) ->
  disp: (@str) ->
    document.getElementById(@id).innerHTML=@str

  add: (@str) ->
      newDiv = document.createElement("div")
      newDiv.innerHTML = @str
      my_div = document.getElementById("org_div1")
      document.getElementById(@id).insertBefore(newDiv, my_div)

  delete: ->
      document.getElementById(@id).innerHTML=""
  
  # ---
  # generated by js2coffee 2.2.0
  
#################################
#ローカルストレージのキーを入れると+マイナスできるクラス
class Cpm
  constructor:(@id) ->
  plus: ->
    getstr = localStorage.getItem(@id)
    num = parseInt(getstr, 10)
    if isNaN(num)
      localStorage.setItem @id, 1
    else
      localStorage.setItem @id, num + 1
  
  minus: ->
    getstr = localStorage.getItem(@id)
    num = parseInt(getstr, 10)
    if isNaN(num)
      localStorage.setItem @id, -1
    else
      localStorage.setItem @id, num - 1

###################################
#ぷらまいクラスを利用して表示とかできるようにした奴
class Cpm_tom
  constructor: ->
    @strdisp = new Disp("str")
    @converter = new showdown.Converter()
    @converter.setOption('tables', 'true')
    @cpm = new Cpm("memo_num")
    
    key = localStorage.getItem("memo_num")
    #文字列を数字に変換
    num = parseInt(key, 10)
    for i in [0..num]
      @strdisp.add(localStorage.getItem(i))
  
  save:(@input) ->
    @cpm.plus()
    input_word = document.getElementById(@input).value
    mark2html = @converter.makeHtml(input_word)
    
    key = localStorage.getItem("memo_num")
    num = parseInt(key, 10)
    localStorage.setItem num, mark2html
    @strdisp.delete()
    for i in [0..num]
      @strdisp.add(localStorage.getItem(i))
      
      
###############################
class Select_strage
  constructor:(@input_key, @input_value) ->
    
  story1:(@key, @value) ->
    document.getElementById(@input_key).value
    localStorage.setItem @key, @value
    
  story2: ->
    key = document.getElementById(@input_key).value
    value = document.getElementById(@input_value).value
    localStorage.setItem key, value

################################
class Add_radio
  constructor:(@div, @name) ->
    @strdisp = new Disp(@div)

  add:(@value, @disp_name) ->
    @strdisp.add("
    <label class=\"item item-radio ng-empty ng-valid\" name=\"#{@name}\" ng-model=\"choice\" ng-value=\"\'#{@value}\'\" value=\"#{@value}\" style=\"\">
    <input type=\"radio\" name=\"#{@name}\" ng-value=\"\'#{@value}\'\" ng-model=\"choice\" class=\"ng-pristine ng-untouched ng-valid ng-empty\" value=\"#{@value}\" style=\"\">
    <div class=\"radio-content\">
    <div class=\"item-content disable-pointer-events\" ng-transclude=\"\">
    <span>#{@disp_name}</span>
    </div>
    <i class=\"radio-icon disable-pointer-events icon ion-checkmark\">
    </i>
    </div>
    </label>
    ")
  
  delete: ->
    this.delete()
  
  story1: ->
      key = localStorage.getItem("memo_num")
      num = parseInt(key, 10)
      for i in [1..num]
        story1_1 = localStorage.getItem(i)
        
        console.log "########"
        console.log story1_1 = localStorage.getItem(i)
        if story1_1 == null
          console.log "nullなんです"
        else
          console.log "nullではないんです"
          story1_2 = JSON.parse(story1_1)
          this.add(i ,story1_2.title)
        console.log "########"
        
        
  
  story2: ->
    $("#"+"#{@div}").click =>
      value = $('input[name=betu]:checked').val()
      key = "getradio"
      localStorage.setItem key, value
  
  story3: ->
    console.log "input[name=#{@name}]"
    doAfter = ->
      radionum = localStorage.getItem("getradio")
      $("input[name=betu]").val [radionum]
    setTimeout(doAfter, 10)
      
##################################
class Select_memo_disp
  constructor:(@div) ->
    @disp = new Disp(@div)
    @value = localStorage.getItem("getradio")
    @value2 = localStorage.getItem(@value)
    @disp.disp(@value2)
  title_memo_disp: ->
    @disp = new Disp(@div)
    @value = localStorage.getItem("getradio")
    @value2 = localStorage.getItem(@value)
    @value3 = JSON.parse(@value2)
    
    @disp2 = new Disp("strtitle")
    @disp2.disp("<h1>#{@value3.title}</h1>")
    
    @converter = new showdown.Converter()
    @converter.setOption('tables', 'true')
    @converter.setOption('simpleLineBreaks', 'false')
    @converter.setOption('disableForced4SpacesIndentedSublists', 'true')
    @converter.setOption('smartIndentationFix', 'false')
    @converter.setOption('strikethrough', 'true')
    
    
    @mark2html = @converter.makeHtml(@value3.memo)
    
    console.log "###########"
    console.log @mark2html
    console.log "###########"
    @mark2html
    @mark2html = @mark2html.replace(/<ul>/g, "")
    #@mark2html = @mark2html.replace("</ul>", "")
    @mark2html = @mark2html.replace("<ol>", "")
    @mark2html = @mark2html.replace("</ol>", "")
    console.log @mark2html
    console.log "###########"
    
    @disp.disp(@mark2html)
    
    
#############################
class Add_title
  constructor:(@input)->
    @cpm = new Cpm("memo_num")
  story2: ->
    console.log "add title"
    @json_title_memo = JSON.stringify({
      title: @test1
      memo: @test2
    })
  
  #あまりセンスがない書き方してるので気を付けるべし
  story1: ->
    @cpm.plus()
    key = localStorage.getItem("memo_num")
    console.log num = parseInt(key, 10)
    @test1 = document.getElementById(@input).value
    
    this.story2()
    
    localStorage.setItem num, @json_title_memo
    
    new Disp("accountdisp").delete()
    addradio = new Add_radio("accountdisp", "betu")
    addradio.story1()
    addradio.story2()
    addradio.story3()
    

##################
class Delete_button
  constructor:->
    console.log "delete ok"
    @key = localStorage.getItem("getradio")
    localStorage.removeItem(@key)
    new Disp("accountdisp").delete()
    addradio = new Add_radio("accountdisp", "betu")
    addradio.story1()
    addradio.story2()
    addradio.story3()
    
      
#################
class Edit_memo
  constructor:->
    console.log "constructor"
    @test2 = localStorage.getItem("getradio")
    @test3 = localStorage.getItem(@test2)
    if @test3 == null
      console.log "null"
      alert "select your memo"
    else
      @test4 = JSON.parse(@test3)
      @title = @test4.title
      @memo = @test4.memo
      
      document.getElementById("titled").value = @title
      document.getElementById("memosd").value = @memo
  save: ->
    console.log "story1"
    @save1 = document.getElementById("titled").value
    @save2 = document.getElementById("memosd").value
    json_title_memo = JSON.stringify({
      title: @save1
      memo: @save2
    })
    @save5 = localStorage.getItem("getradio")
    if @test3 == null
      console.log "null"
    else
      localStorage.setItem @save5, json_title_memo

##################
class Title_and_memo
  constructor:->
    console.log "new Title_and_memo"
  save:->
    console.log "save Title_and_memo"
    @test1 = document.getElementById("titled").value
    @test2 = document.getElementById("memosd").value
    
    json_title_memo = JSON.stringify({
      title: @test1
      memo: @test2
    })
    console.log json_title_memo
    obj = JSON.parse(json_title_memo)
    console.log obj.title
    console.log obj.memo

#########################
class Area_auto_size
  constructor:(@id) ->
      console.log "Area_auto_size"
      console.log @target_id  = "##{@id}"
      $(@target_id).height 30
      $(@target_id).css 'lineHeight', '20px'
      $(@target_id).on 'input', (evt) ->
        console.log "####evt = #{evt}"
        console.log $('#memosd').focus()
        if evt.target.scrollHeight > evt.target.offsetHeight
          $(evt.target).height evt.target.scrollHeight
        else
          lineHeight = Number($(evt.target).css('lineHeight').split('px')[0])
          loop
            $(evt.target).height $(evt.target).height() - lineHeight
            if evt.target.scrollHeight > evt.target.offsetHeight
              $(evt.target).height evt.target.scrollHeight
              break
        return
      
  story1:->
      $(@target_id).height 30
      $(@target_id).css 'lineHeight', '20px'
      console.log obj = $("#memosd").get(0)
      if obj.scrollHeight > obj.offsetHeight
          $(obj).height obj.scrollHeight
      else
        lineHeight = Number($(obj).css('lineHeight').split('px')[0])
        loop
          $(obj).height $(obj).height() - lineHeight
          if obj.scrollHeight > obj.offsetHeight
            $(obj).height obj.scrollHeight
            break
        return
      
###########################
class Delete_strage
  constructor:(@delkey) ->
    console.log @delkey
    @const1 = document.getElementById(@delkey).value
    console.log @const1
    localStorage.removeItem(@const1)
    
    
########################
class Insert_caret
  constructor:(@target, @str) ->
    obj = $("##{@target}")
    obj.focus()
    if navigator.userAgent.match(/MSIE/)
      r = document.selection.createRange()
      r.text = @str
      r.select()
    else
      s = obj.val()
      p = obj.get(0).selectionStart
      np = p + @str.length
      obj.val s.substr(0, p) + @str + s.substr(p)
      obj.get(0).setSelectionRange np, np
    return

############################
class End_and_home
  constructor:() ->
    
  home:->
    obj = $('#memotest').focus()
    console.log obj.get(0).selectionStart
    
    t = document.getElementById('memosd')
    len = t.value.length
    t.focus()
    t.setSelectionRange 0, 0
    
  end:->
    $('#memotest').focus()
    t = document.getElementById('memosd')
    len = t.value.length
    t.focus()
    t.setSelectionRange len, len
    